server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ARTSLocal
    username: root
    password: 123Railink2016!
    tomcat:
      log-abandoned: true
      max-active: 1000


